// <auto-generated />
using System;
using Lama.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lama.Server.Data.Migrations
{
    [DbContext(typeof(LamaDbContext))]
    [Migration("20260703091106_AddPlayerAccessibilityPreferences")]
    partial class AddPlayerAccessibilityPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lama.Server.Data.Models.History.CompletedGameEntity", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int>("BoardSize")
                        .HasColumnType("integer")
                        .HasColumnName("board_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("GameLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("game_level");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<int>("MinWordLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_word_length");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("queue");

                    b.Property<int>("RackSize")
                        .HasColumnType("integer")
                        .HasColumnName("rack_size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("WinningPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winning_player_id");

                    b.HasKey("GameId");

                    b.HasIndex("EndedAt");

                    b.HasIndex("Queue");

                    b.ToTable("completed_games", "history");
                });

            modelBuilder.Entity("Lama.Server.Data.Models.Rating.PlayerEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("player_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessibilityPreferencesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("accessibility_preferences_json");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("PlayerId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("players", "rating");
                });

            modelBuilder.Entity("Lama.Server.Data.Models.Rating.PlayerRatingEntity", b =>
                {
                    b.Property<Guid>("RatingRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rating_record_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AvgScore")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("avg_score");

                    b.Property<decimal>("EloRating")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("elo_rating");

                    b.Property<int>("GamesAbandoned")
                        .HasColumnType("integer")
                        .HasColumnName("games_abandoned");

                    b.Property<int>("GamesLost")
                        .HasColumnType("integer")
                        .HasColumnName("games_lost");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<int>("GamesWon")
                        .HasColumnType("integer")
                        .HasColumnName("games_won");

                    b.Property<DateTimeOffset?>("LastGameDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_game_date");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("queue");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("total_points");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RatingRecordId");

                    b.HasIndex("PlayerId", "Queue")
                        .IsUnique();

                    b.HasIndex("Queue", "EloRating");

                    b.ToTable("player_ratings", "rating");
                });

            modelBuilder.Entity("Lama.Server.Data.Models.Sessions.SessionBoardStateEntity", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("BoardJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("board_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GameId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("board_state", "sessions");
                });

            modelBuilder.Entity("Lama.Server.Data.Models.Sessions.SessionGameEntity", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("game_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BoardSize")
                        .HasColumnType("integer")
                        .HasColumnName("board_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("GameLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("game_level");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<int>("MinWordLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_word_length");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("queue");

                    b.Property<int>("RackSize")
                        .HasColumnType("integer")
                        .HasColumnName("rack_size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GameId");

                    b.HasIndex("Queue");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("games", "sessions");
                });

            modelBuilder.Entity("Lama.Server.Data.Models.Sessions.SessionPlayerInGameEntity", b =>
                {
                    b.Property<Guid>("PlayerSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("player_session_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsHost")
                        .HasColumnType("boolean")
                        .HasColumnName("is_host");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("PlayerIndex")
                        .HasColumnType("integer")
                        .HasColumnName("player_index");

                    b.HasKey("PlayerSessionId");

                    b.HasIndex("GameId");

                    b.HasIndex("IsHost");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("GameId", "PlayerIndex")
                        .IsUnique();

                    b.ToTable("players_in_game", "sessions");
                });

            modelBuilder.Entity("Lama.Server.Data.Models.Sessions.SessionTurnLogEntity", b =>
                {
                    b.Property<Guid>("TurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("action_payload");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("PlayerSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_session_id");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result_status");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.HasKey("TurnId");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerSessionId");

                    b.HasIndex("GameId", "TurnNumber");

                    b.ToTable("turn_log", "sessions");
                });

            modelBuilder.Entity("Lama.Server.Data.Models.Rating.PlayerRatingEntity", b =>
                {
                    b.HasOne("Lama.Server.Data.Models.Rating.PlayerEntity", "Player")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Lama.Server.Data.Models.Rating.PlayerEntity", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
